openapi: 3.0.0
info:
  title: Leaderbored
  description: A basic leaderboard API
  version: 0.0.1

servers:
  - url: https://api.example.com/v1
    description: Optional server description, e.g. Main (production) server

paths:
  /top:
    get:
      summary: Return a list of the current leaderboard
      responses:
        "200": # status code
          description: A JSON array of user names and the score
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    name:
                      description: Name of the user
                      type: string
                    score:
                      description: score of the user
                      type: integer
                      format: int64
  /add:
    post:
      summary: Update or add a entry to the leaderboard
      request:
      responses:
        "200": # status code
          description: A secret for the client to update their record
          content:
            application/json:
              schema:
                type: string
      requestBody:
        content:
          application/json:
            schema:
            type: object
            properties:
                name:
                  description: Name of the user
                  type: string
                score:
                  description: score of the user
                  type: integer
                  format: int64
                secret:
                  description: optional secret used to update a record
                  type: string
            required:
              - name
              - score 